name: ebbinghaus_forgetting_curve
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  go_router: ^13.0.1
  flutter_svg: ^2.0.9
  table_calendar: ^3.0.9
  intl: ^0.18.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  freezed: ^2.4.6
  flutter_hooks: ^0.20.4
  hooks_riverpod: ^2.4.9
  flutter_slidable: ^3.0.1
  flutter_localizations:
      sdk: flutter
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.0.15
  percent_indicator: ^4.2.3
  flutter_colorpicker: ^1.0.3
  flutter_native_splash:
  flutter_local_notifications: ^17.0.0
  permission_handler:
  package_info: ^2.0.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.8
  custom_lint: ^0.5.8
  # riverpod_lint: ^2.3.7
  json_serializable: ^6.7.1
  isar_generator: ^3.1.0+1


flutter_native_splash:
  color: '#add8e6'
  image: assets/picture/dorapoyoron.png
  android: true
  ios: true
  fullscreen: true

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/picture/

  fonts:
    - family: Inter
      fonts:
       - asset: assets/fonts/Inter/static/Inter-Thin.ttf
         weight: 100
       - asset: assets/fonts/Inter/static/Inter-ExtraLight.ttf
         weight: 200
       - asset: assets/fonts/Inter/static/Inter-Light.ttf
         weight: 300
       - asset: assets/fonts/Inter/static/Inter-Regular.ttf
         weight: 400
       - asset: assets/fonts/Inter/static/Inter-Medium.ttf
         weight: 500
       - asset: assets/fonts/Inter/static/Inter-SemiBold.ttf
         weight: 600
       - asset: assets/fonts/Inter/static/Inter-Bold.ttf
         weight: 700
       - asset: assets/fonts/Inter/static/Inter-ExtraBold.ttf
         weight: 800
       - asset: assets/fonts/Inter/static/Inter-Black.ttf
         weight: 900

